# Generated by Django 2.1.7 on 2020-06-08 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouped',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouped',
            name='user',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Grouped',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
