# Generated by Django 2.1.7 on 2020-06-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssim', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssim.Image'),
        ),
    ]
